fun main() {
    println()
    println()
    println()
    println()
    println()
    println("Jules: Do you know what they call a Quarter Pounder with cheese in France?")
    Thread.sleep(1000)
    println("Brett:")
    var convo1 = readln()
    println("\nJules: Tell him, Vincent.")
    Thread.sleep(1000)
    println("Vincent: Royale with cheese.")
    Thread.sleep(1000)
    println("Jules: Royale with cheese!")
    Thread.sleep(1000)
    println("Jules: Do you know why they call it a Royale with cheese?")
    Thread.sleep(1000)
    println("Brett: Because of the..")
    var convo2 = readln()
    println("\nJules: That's right, because of the $convo2!")
    Thread.sleep(1000)
    println("Check out the big brain on Brett. You one smart motherfucker.")
    var final = readln()
    println("")
    println("")
    println("⠌⠊⠆⠕⠅⠕⠌⡆⣃⠪⠢⠣⡱⡑⢕⢅⢣⠱⡡⡣⡣⡣⡣⠄⠄⠄⠄⠄⠄⠄⠄⢀⣀⣠⣀⢀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠄⡀⡀⡀⡀⡀⡀⢄⠢⢀⠄⡁⢀⠠⠄⠄⡀⠅⠈⡈⢸⢸⢪⠄⠄⠄⠄⠄⢀⣴⣿⣿⡿⣿⡟⣿⣻⣆⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠪⡐⡌⢆⢎⢢⠶⠿⠻⡟⠻⠾⠰⡕⡝⡜⣔⢕⢕⠄⡣⡣⡣⠄⠄⠄⠄⢰⣿⣿⡿⠯⠘⠄⠁⠄⠄⠉⢢⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⡊⢔⠜⡌⠎⢈⣬⣥⣤⣴⣶⠄⠄⠈⢪⡳⣕⡕⡧⡁⣇⢇⢇⠄⠄⠄⢀⣿⡏⠈⠄⠄⠄⠄⠄⠄⠄⠄⠄⡃⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⡨⠢⡑⡕⠄⢐⣿⣿⡿⠿⠟⢧⠄⠄⠘⣞⡞⡮⡳⡁⣇⢇⠧⠄⠄⠄⠄⢇⡂⠄⠄⠄⡄⠄⠄⠄⢠⢀⠄⠐⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠠⡑⢌⢺⡀⠰⣤⣖⣯⢶⣽⣟⠆⡄⠄⣗⡯⣯⣣⠃⣇⢇⢏⠄⠄⠄⠄⠄⠐⣠⡖⡦⣽⡿⢆⠄⠚⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⢐⠨⡐⣝⣇⠄⣝⣯⢭⢽⣻⡺⠅⠄⠄⣿⢽⣳⣳⠁⢱⢱⡑⠄⠄⠄⠄⠄⠄⠃⠈⠢⢕⠝⠐⠄⡑⠄⣄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⣔⣅⣆⣗⢿⡀⢐⢡⢭⢼⠸⠈⠄⠄⠄⣻⣟⣷⢷⢅⡇⡇⡇⠄⠄⠄⠄⠄⠄⠄⠅⠡⠄⠄⠄⠂⣊⣼⣿⠄⢠⣀⡀⠄⠄⠄⠄⠄")
    println("⣿⡯⠏⠃⠋⠃⠘⣷⣄⡀⢀⣤⠆⡄⠄⠛⣛⢙⢋⠃⢗⡝⡌⠄⣠⣤⣶⣶⡲⡶⡲⡆⢒⣶⠂⣾⣿⣿⡟⠄⠄⠙⠻⡿⡶⣦⣤⡀")
    println("⠛⠈⠄⠄⠄⠄⠄⢻⣿⡯⢩⣿⣿⣥⠄⠄⠄⠄⠉⠛⣿⣎⢇⢀⢼⠌⠪⠁⠄⢙⠽⠻⢸⠏⠐⣿⣿⣿⠇⠄⠄⠄⠄⠠⠁⠄⠠⠃")
    println("⠄⠄⠄⠄⠄⣀⣤⣼⡿⠗⡚⢛⣯⢿⠄⠄⠄⠄⠄⠄⢸⣯⣧⡶⠶⠇⠄⠄⠄⠄⠄⠄⢸⠄⠄⣿⣿⡿⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠄⠄⠄⠄⠄⣝⠁⢐⣀⢁⠄⠆⠊⠚⠛⢢⣤⣶⣶⣿⣿⣿⢭⡛⠂⠄⠄⠄⠄⠄⠄⠄⡎⠄⢸⣿⣿⡇⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠄⠄⠄⠄⠄⠄⠄⢸⡧⢸⠄⠁⠄⠄⠄⠄⠉⣮⠃⠁⠈⠉⠉⠄⠄⠄⠄⠄⠄⠄⠄⠄⡇⠄⢸⣿⣿⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠄⠄⠄⠄⠄⠄⠄⣸⣝⢈⡇⠄⠄⠬⠐⠄⠄⡼⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢰⠁⠄⢸⣿⡏⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠄⠄⠄⠄⠄⠄⠄⣿⣿⡄⠁⢰⣶⣏⠄⠄⠁⠄⠄⠄⠄⠸⣟⠄⡁⠄⠄⠄⠄⠄⠄⢸⠄⠄⢸⣿⠃⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠄⠄⠄⠄⠄⠄⢰⣿⣿⠁⠄⠈⣷⣧⠄⠄⠄⠄⠄⠄⠄⠄⣗⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢸⠭⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
    println("⠄⠄⠄⠄⠄⠄⢸⣿⣿⠇⠄⠄⣿⡏⠄⠄⠄⠄⠄⠄⠄⠄⡳⠄⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⢸⡑⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
}

// TESTrghrtzhrnj
